/*
 * RPG Game - Software Engineering * All rights reserved
 * Konrad Rugala, Krzysztof Sobieraj
 */
package com.rpg.windows;



/**
 *
 * @author Darkrage
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        setLocationRelativeTo(null);
        setUndecorated(true);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        welcomePanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        logButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        footerLabel = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        registerLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        repassLabel = new javax.swing.JLabel();
        acceptRegButton = new javax.swing.JButton();
        cancelRegButton = new javax.swing.JButton();
        loginRegTextField = new javax.swing.JTextField();
        passwordRegPassField = new javax.swing.JPasswordField();
        repassRegPassField = new javax.swing.JPasswordField();
        logPanel = new javax.swing.JPanel();
        loginTitleLogLabel = new javax.swing.JLabel();
        loginLogLabel = new javax.swing.JLabel();
        passwordLogLabel = new javax.swing.JLabel();
        loginLogTextField = new javax.swing.JTextField();
        passwordLogPassField = new javax.swing.JPasswordField();
        acceptLogButton = new javax.swing.JButton();
        cancelLogButton = new javax.swing.JButton();
        accountPanel = new javax.swing.JPanel();
        accountTitleLabel = new javax.swing.JLabel();
        logingetAccLabel = new javax.swing.JLabel();
        logoutAccButton = new javax.swing.JButton();
        avaibleAccLabel = new javax.swing.JLabel();
        characterAccList = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        lastAccList = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        createAccButton = new javax.swing.JButton();
        deleteCharAccButton = new javax.swing.JButton();
        startAccButton = new javax.swing.JButton();
        deleteAccAccButton = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        closeMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        MainPanel.setPreferredSize(new java.awt.Dimension(860, 500));
        MainPanel.setLayout(null);

        welcomePanel.setPreferredSize(new java.awt.Dimension(860, 500));

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        welcomeLabel.setText("Welcome to graRPG");

        logButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        logButton.setText("Log in");
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        registerButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        footerLabel.setText("Created by Konrad Rugała and Krzysztof Sobieraj");

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(logButton, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(welcomeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(footerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(welcomePanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(welcomePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(148, 148, 148)
                .addComponent(footerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainPanel.add(welcomePanel);
        welcomePanel.setBounds(0, 0, 860, 500);

        registerPanel.setEnabled(false);
        registerPanel.setPreferredSize(new java.awt.Dimension(860, 500));

        registerLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        registerLabel.setText("Register");

        loginLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loginLabel.setText("Login:");

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        passwordLabel.setText("Password:");

        repassLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        repassLabel.setText("Retype Password:");

        acceptRegButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        acceptRegButton.setText("Accept");

        cancelRegButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cancelRegButton.setText("Cancel");

        loginRegTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loginRegTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginRegTextFieldActionPerformed(evt);
            }
        });

        passwordRegPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordRegPassFieldActionPerformed(evt);
            }
        });

        repassRegPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repassRegPassFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(acceptRegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(cancelRegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(registerLabel))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginLabel)
                            .addComponent(passwordLabel)
                            .addComponent(repassLabel))
                        .addGap(145, 145, 145)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordRegPassField)
                            .addComponent(repassRegPassField, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                            .addComponent(loginRegTextField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acceptRegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(registerLabel)
                        .addGap(42, 42, 42)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginLabel)
                            .addComponent(loginRegTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordLabel)
                            .addComponent(passwordRegPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(repassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(repassRegPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(cancelRegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        MainPanel.add(registerPanel);
        registerPanel.setBounds(0, 0, 860, 500);

        logPanel.setEnabled(false);

        loginTitleLogLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        loginTitleLogLabel.setText("Log in");

        loginLogLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loginLogLabel.setText("Login:");

        passwordLogLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        passwordLogLabel.setText("Password:");

        passwordLogPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordLogPassFieldActionPerformed(evt);
            }
        });

        acceptLogButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        acceptLogButton.setText("Accept");
        acceptLogButton.setPreferredSize(new java.awt.Dimension(103, 37));

        cancelLogButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cancelLogButton.setText("Cancel");

        javax.swing.GroupLayout logPanelLayout = new javax.swing.GroupLayout(logPanel);
        logPanel.setLayout(logPanelLayout);
        logPanelLayout.setHorizontalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logPanelLayout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(loginTitleLogLabel))
                    .addGroup(logPanelLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginLogLabel)
                            .addComponent(passwordLogLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginLogTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                            .addComponent(passwordLogPassField))))
                .addGap(103, 103, 103))
            .addGroup(logPanelLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(acceptLogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(cancelLogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        logPanelLayout.setVerticalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(loginTitleLogLabel)
                .addGap(55, 55, 55)
                .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginLogLabel)
                    .addComponent(loginLogTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordLogLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordLogPassField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelLogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acceptLogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        MainPanel.add(logPanel);
        logPanel.setBounds(-32768, -32768, 100, 100);

        accountPanel.setEnabled(false);

        accountTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        accountTitleLabel.setText("Account");

        logingetAccLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        logingetAccLabel.setText("Login");

        logoutAccButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        logoutAccButton.setText("Logout");
        logoutAccButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutAccButtonActionPerformed(evt);
            }
        });

        avaibleAccLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        avaibleAccLabel.setText("Avaible Characters:");

        jList1.setBackground(new java.awt.Color(240, 240, 240));
        jList1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Character 1", "Character 2" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setFixedCellHeight(50);
        jList1.setFixedCellWidth(20);
        characterAccList.setViewportView(jList1);

        lastAccList.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        lastAccList.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jList2.setBackground(new java.awt.Color(240, 240, 240));
        jList2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Last 1", "Last 2", "" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList2.setFixedCellHeight(50);
        jList2.setFixedCellWidth(20);
        lastAccList.setViewportView(jList2);

        createAccButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createAccButton.setText("Create New Character");

        deleteCharAccButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deleteCharAccButton.setText("Delete Character");

        startAccButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        startAccButton.setText("Start Game");

        deleteAccAccButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deleteAccAccButton.setText("Delete Account");

        javax.swing.GroupLayout accountPanelLayout = new javax.swing.GroupLayout(accountPanel);
        accountPanel.setLayout(accountPanelLayout);
        accountPanelLayout.setHorizontalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(accountTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logingetAccLabel)
                .addGap(18, 18, 18)
                .addComponent(logoutAccButton)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountPanelLayout.createSequentialGroup()
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avaibleAccLabel)
                            .addGroup(accountPanelLayout.createSequentialGroup()
                                .addComponent(characterAccList, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lastAccList, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(125, 125, 125))
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(startAccButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteAccAccButton)
                    .addComponent(createAccButton)
                    .addComponent(deleteCharAccButton))
                .addGap(134, 134, 134))
        );
        accountPanelLayout.setVerticalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(logingetAccLabel)
                                .addComponent(logoutAccButton))
                            .addComponent(accountTitleLabel))
                        .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(accountPanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(avaibleAccLabel))
                            .addGroup(accountPanelLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(createAccButton)))
                        .addGap(12, 12, 12)
                        .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(characterAccList, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(lastAccList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(deleteCharAccButton))
                .addGap(83, 83, 83)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startAccButton)
                    .addComponent(deleteAccAccButton))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        MainPanel.add(accountPanel);
        accountPanel.setBounds(0, 0, 860, 500);

        getContentPane().add(MainPanel);
        MainPanel.setBounds(-32768, -32768, 100, 100);

        jMenuBar.setBackground(new java.awt.Color(255, 255, 255));

        closeMenu.setBorder(null);
        closeMenu.setText("Close");
        closeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMenuMousePressed(evt);
            }
        });
        jMenuBar.add(closeMenu);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButtonActionPerformed

    private void loginRegTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginRegTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginRegTextFieldActionPerformed

    private void passwordRegPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordRegPassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordRegPassFieldActionPerformed

    private void repassRegPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repassRegPassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repassRegPassFieldActionPerformed

    private void passwordLogPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordLogPassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordLogPassFieldActionPerformed

    private void closeMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMenuMousePressed
        System.exit(0);
    }//GEN-LAST:event_closeMenuMousePressed

    private void logoutAccButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutAccButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutAccButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton acceptLogButton;
    private javax.swing.JButton acceptRegButton;
    private javax.swing.JPanel accountPanel;
    private javax.swing.JLabel accountTitleLabel;
    private javax.swing.JLabel avaibleAccLabel;
    private javax.swing.JButton cancelLogButton;
    private javax.swing.JButton cancelRegButton;
    private javax.swing.JScrollPane characterAccList;
    private javax.swing.JMenu closeMenu;
    private javax.swing.JButton createAccButton;
    private javax.swing.JButton deleteAccAccButton;
    private javax.swing.JButton deleteCharAccButton;
    private javax.swing.JLabel footerLabel;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane lastAccList;
    private javax.swing.JButton logButton;
    private javax.swing.JPanel logPanel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel loginLogLabel;
    private javax.swing.JTextField loginLogTextField;
    private javax.swing.JTextField loginRegTextField;
    private javax.swing.JLabel loginTitleLogLabel;
    private javax.swing.JLabel logingetAccLabel;
    private javax.swing.JButton logoutAccButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLogLabel;
    private javax.swing.JPasswordField passwordLogPassField;
    private javax.swing.JPasswordField passwordRegPassField;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JLabel repassLabel;
    private javax.swing.JPasswordField repassRegPassField;
    private javax.swing.JButton startAccButton;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
